#!/bin/bash

eval "sudo killall openvpn";
sleep 2;
OIFS=$IFS; 
IFS=$'\n'; 
array=($(find . -name "*.ovpn")); 
IFS=$OIFS; 
rand=$[$RANDOM % ${#array[@]}];
echo "${array[$rand]}";
eval "sudo openvpn --config '${array[$rand]}' --float --auth-user-pass pass.txt &"
#sleep 300;
#eval "bash $0"
